application: wave-extensions
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /gallery(/.*)?
  script: gallery.py

- url: /dev(/.*)?
  script: dev.py

- url: /.*
  script: main.py
