application: wave-extensions-gallery
version: ui2
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /account(/.*)?
  script: accounts.py

- url: /api(/.*)?
  script: api.py

- url: /dev(/.*)?
  script: dev.py

- url: /docs(/.*)?
  script: docs.py

- url: /gallery(/.*)?
  script: gallery.py

- url: /.*
  script: main.py
