application: wave-extensions-gallery
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /account(/.*)?
  script: accounts.py

- url: /dev(/.*)?
  script: dev.py

- url: /gallery(/.*)?
  script: gallery.py


- url: /.*
  script: main.py
