SEARCH_INDEX_NAME = 'galleryindex'

DEFAULT_QUERY_LIMIT = 20
DEFAULT_QUERY_OFFSET = 0

DEFAULT_EXTENSION_TITLE = ''
DEFAULT_EXTENSION_DESCRIPTION = ''
DEFAULT_EXTENSION_TYPE = 'gadget'
DEFAULT_EXTENSION_CATEGORY = 'other'

SORT_TOP_RATING = 'rating'
SORT_BEST_MATCH = 'match'
